### ISSUE TITLE
MouseClick, left clicks to 0,0 in KDE/plasma not to actual position

### ISSUE THREAD

**Issue by peterlopen** [phil294/AHK_X11#16]
hi,

Operating System: Kubuntu 22.04
KDE Plasma Version: 5.24.6
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3

following script:

#a::MouseClick, left

clicks to left top corner when pressing win+a, not to actual mouse position.
(same with other key combinations)

thank you.

regards,
peter

**Comment by phil294** [comment]
Hello,

`MouseClick` is currently only very basic ([link to docs](https://phil294.github.io/AHK_X11/#MouseClick.htm)). However, you're right because the docs say `If omitted, the current position is used.` which is not the case. So, sorry, for now please specify coordinates or wait a few days to weeks until I've properly implemented the command.

**Comment by peterlopen** [comment]
actually, I want to click to current position :) just emulate mouse click by key combination
based on https://phil294.github.io/AHK_X11/#MouseGetPos.htm I assume get pos is not implemented, or is it? thank you.

**Comment by phil294** [comment]
> actually, I want to click to current position :) 

yeah, this is (was) not possible, that's what I meant by `which is not the case.`. Sorry if I was being unclear.

However, it's fixed now, as I have properly implemented `MouseClick` and `MouseMove` and `MouseGetPos` (yes, was also missing).

You'll be able to try it out with the next release - not sure when yet.

thanks for the report!

**Comment by peterlopen** [comment]
thanks for clarification and fix. looking forward for next release. thank you!

shall I close this issue?
