### ISSUE TITLE
Cannot compile with Crystal from homebrew

### ISSUE THREAD

**Issue by BySylex** [phil294/AHK_X11#20]
There problem.
```
/usr/bin/ld: warning: libpcre.so.3, needed by /lib/x86_64-linux-gnu/libglib-2.0.so.0, may conflict with libpcre.so.1
/root/.cache/crystal/crystal-run-build_namespace.tmp: error while loading shared libraries: libpcre.so.1: cannot open shared object file: No such file or directory

```

**Comment by phil294** [comment]
Hi!

1. what system are you using? (e.g. Ubuntu 22.04)
2. how did you install Crystal?

I can investigate this problem only in about 10 days, and try to replicate it given you provide the above info. But if you need an urgent fix, I guess you need to somehow install libpcre version 1 instead of 3, although I have no idea why... and who knows if there may arise other dependency errors after that.

**Comment by BySylex** [comment]
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"

**Comment by phil294** [comment]
will most likely be fixed with next release, with is  just a few days away.

**Comment by phil294** [comment]
...in case you didn't know, you don't have to run this script to get ahk11 running, because there is also a ready to use binary. From the readme:

> You don't need to follow this procedure to use AHK_X11, for that, please see Installation above.

**Comment by phil294** [comment]
actually, I didn't solve this, sorry... it's not related to the libssl bug as I thought.

So to fix this, I think you just need to install Crystal normally via their PPA (`curl -fsSL https://crystal-lang.org/install.sh | sudo bash`), **or**... I'd suggest you just download the latest release and use that instead, no need to download Crystal if you just want to code in AHK. that is, unless you really wanted to build from source, of  course :-)
