### ISSUE TITLE
Repeated keypresses not being suppressed

### ISSUE THREAD

**Issue by picklepissjar** [phil294/AHK_X11#33]
OS:
Arch Linux x86_64 6.1.7
KDE Plasma 5.26.5

Problem:
Past the first key press the key is not being suppressed when triggering a hotkey.

Steps taken to fix:
Restarting
Disabling ibus, autokey (other keyboard related applications)

Steps to reproduce:
-Run the following code:
g::return
h::Send, a
-observe behavior on repeated presses

Comments:
In the above example the g key would sort of be suppressed (Worked within VSC for a bit, but restarting VSC "breaks" the suppression), but the h keys output would look like [a, ha, ha, ha, ha, ...]
Is this intended behavior?
I like the project btw :)

**Comment by phil294** [comment]
hello,

thanks for the report. This is indeed a bug which I already fixed a few weeks ago on the dev branch in 0da72d1. This fix is not released yet and I'm not yet sure when that will happen, so for now you either need to build the project locally or use version 0.3.0, as this bug was introduced in 0.4.0 and absent prior. 0.4.0 added and fixed a lot of stuff though, so you'll have to see if this suits you.

To be clear, what's happening is that any `Send`-like command (in your case, `Send, a`) disables the "grab" on all previously registered hotkeys but failed to restore it afterwards.

**Comment by picklepissjar** [comment]
I've successfully built the dev branch locally, and it is working properly :D.
I also ran into the private method error, #31 . Changing the method to public fixed it for me.
TY.

**Comment by phil294** [comment]
fyi you should now be able to use official 0.5.0 for this too
