### ISSUE TITLE
key name 'j' not found

### ISSUE THREAD

**Issue by toimine** [phil294/AHK_X11#43]
i'm trying to run a simple script that used to work on windows (i've attached it), but somehow this is what trips up the app, even though the documentation file mentions remapping keys like this without any strikethroughs
in case my installation process was wrong: i've downloaded the latest appimage, then ran "chmod +x ./ahk_x11-0.5.1-x86_64.AppImage" in the folder with ahk, launched the file and pressed the install button to install it
[a.ahk.txt](https://github.com/phil294/AHK_X11/files/11122753/a.ahk.txt)

**Comment by phil294** [comment]
yes, most likely the file was BOM-encoded or with `\r\n` instead of `\n` (#5).

> even though the documentation file mentions remapping keys like this without any strikethroughs

I'm not very sure what you mean by that, as [the entire section about key remapping is crossed out](https://phil294.github.io/AHK_X11/#Remap.htm). So yeah traditional win-ahk-like key remaps aren't supported yet. For now you'll have to do
```ahk
a::Send, {Left}
```
but it's quite more limited. Hopefully I'll get to fix this in the next few weeks though.

**Comment by toimine** [comment]
oh, so that's where that section was
i saw similar syntax in hotkeys

**Comment by phil294** [comment]
syntax like `a::left` should work now! so I guess we can close this.
