### ISSUE TITLE
Fails to parse utf8 BOM encoded files

### ISSUE THREAD

**Issue by Drugoy** [phil294/AHK_X11#5]
Currently they cause "Syntax Error in line X: Command '/*' not found."

**Comment by phil294** [comment]
could you please share some code? as far as I can tell, it works as it should.

**Comment by Drugoy** [comment]
https://github.com/Drugoy/Autohotkey-scripts-.ahk/blob/master/DrugWinManager/DrugWinManager.ahk

**Comment by phil294** [comment]
found the problem, it's because your linked file is saved as `UTF-8 with BOM`. Any command fails, not just `/*`

I don't really remember the point of BOMs, but https://unix.stackexchange.com/a/381237/103120 says

> A BOM doesn't make sense in UTF-8. Those are generally added by mistake by bogus software on Microsoft OSes.

so for now I guess just do `dos2unix DrugWinManager.ahk` once.

ahkx11 should eventually also support utf-bom, and also \r\n delimited text files (I assume that doesn't work either).

Regarding the script itself, I guess it was just for demo purposes? Because in case you don't know, you can in no way just execute windows ahk scripts with this very tool

**Comment by Drugoy** [comment]
Thanks for evaluating the real issue here and editing this ticket.
As for the script itself - I've recently just learned about ahk_x11 and I don't yet know what it's capable of at all and what I actually need from it now that I live on linux.
I guess, most of all I miss proper hotstringing (on the level that AHK delivered it on Windows).

**Comment by phil294** [comment]
non-utf8 or bom-files will now (upcoming release) just be rejected with an explicit message at startup, that's good enough for me
