### ISSUE TITLE
the command [SetNumLockState] [SetScrollLockState] [SetCapsLockState] [GetKeyState] 

### ISSUE THREAD

**Issue by againo** [phil294/AHK_X11#62]
i am a ubuntu 22.04TLS, first i want to thanks author about the program ahk_x11,it is great ! :)
## ques:
the command `SetNumLockState` `SetScrollLockState` `SetCapsLockState` `GetKeyState` are not sopport yet?
i am about to make my input like in macOS,then the error says these command not known
though, i found another write way to accomplish my think.
maybe someone also want it, so i post it out:
```
CapsLock::
KeyWait, CapsLock, T0.5 
If ErrorLevel = 0
    Send ^{Space}
Else
    Send {CapsLock}
return
```

**Comment by phil294** [comment]
Hi, thank you! To find out which commands are supported, it's best to check the documentation: https://phil294.github.io/AHK_X11/#SetNumScrollCapsLockState.htm here you can see that `SetNumLockState` etc. are crossed out, so they are not available yet.

`GetKeyState` however is supported. https://phil294.github.io/AHK_X11/#SetNumScrollCapsLockState.htm

With that said, I have found hotkeys and `Send` commands containing `CapsLock` to behave rather erroneous because the original caps function can't quite be overwritten. But I'm glad it works out for you!
