### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by Freso** [phil294/AHK_X11#76]
I see the `LICENSE` file is GPL 2.0, but `shard.yml` states the project license as [`MIT`](https://spdx.org/licenses/MIT.html). There’s no copyright notice that I can find in source code headers to clarify if it’s a case of different files being differently licensed. Additionally, if it _is_ meant to be GPL’d, the lack of source code header copyright blurbs also means it isn’t clear whether this is released under [`GPL-2.0-only`](https://spdx.org/licenses/GPL-2.0-only.html) or [`GPL-2.0-or-later`](https://spdx.org/licenses/GPL-2.0-or-later.html). 

Clarification of the licensing would be appreciated!

**Comment by phil294** [comment]
Hi, thanks for noting, the value in shard.yml was indeed wrong, I have fixed it. It should all be GPL-2.0.

Regarding -only or -or-later: I have no idea and don't really care, as GPL-3.0 is also fine with me. GPL is a good license and it's taken over from mainstream [Windows AHK](https://github.com/AutoHotkey/AutoHotkey) which is also GPL 2. Do I really need to specify this somewhere in detail?

Also, just in case you're planning on making an AUR package, this is already underway / mostly complete by someone else, just need to clarify some final steps there :)

**Comment by Freso** [comment]
Ah, alright. Looks like Windows AHK has the <q>, or (at your option) any later version</q> bit in their copyright blurbs (e.g., [source/util.cpp](https://github.com/AutoHotkey/AutoHotkey/blob/alpha/source/util.cpp#L9)), so I’ll update the AUR packages accordingly.

And yeah, I was working on exactly that, and already did [`ahk_x11`](https://aur.archlinux.org/packages/ahk_x11) and [`ahk_x11-git`](https://aur.archlinux.org/packages/ahk_x11-git). Didn’t realise someone else was working on it too. Sorry! I can add them in as a maintainer as well if they want.

**Comment by phil294** [comment]
ok fine!

Wow, sweet, thanks for your efforts! Both packages seem to work perfectly.

The other AUR maintainer might get in touch with you soon. I've been in exchange with him for a while because there were several changes I needed to make to the build process for everything to work fine. I have suggested to him to build or publish the AppImage build, though, because without it, compiled scripts are not portable. You have probably read it, but it's explained [here](https://github.com/phil294/AHK_X11/blob/master/build/README.md#for-making-release-like-binaries). Especially since most ahk_x11 users will probably be familiar with windows ahk and have migrated to Linux at some point, the backwards-compatible compilation features is something I would like to preserve as much as possible.

Because of this, my suggestion would be for him to make an `ahk_x11-bin` AUR package. Eventually, I will link to all three packages in this project's Readme, while recommending the `-bin` one for most users.

It might even make sense to build a fourth version, `ahk_x11-appimage`, so to build the AppImage from source. This probably requires a Docker dependency and might be a bit of an overkill, so I'm not too sure here...

Anyway, regarding the two of yours, I think you may be able to drop the `fuse2` dependency, as it's only a runtime dependency for AppImages.

**Comment by Freso** [comment]
I will. :) Thanks for your feedback and your clarification! I think this issue is resolved.
