### ISSUE TITLE
The IfWinActive command does not work as expected

### ISSUE THREAD

**Issue by SN-CH** [phil294/AHK_X11#78]
First and most important of all thank you very much for the job you have done. Those who are used to AHK in Windows are truly missing its equivalent in Linux world.

I have a question about the `IfWinActive` command. Please take a look at the following script (the goal is to be able to use the mouse wheel button to go to the previous page in browsers, for example Chrome, while keeping its normal functionality untouched in other programs).
```
IfWinActive, ahk_class Google-chrome
{
  MButton::
    Send, !{Left}
    Return
}
Else
{
  $MButton::
    Send, MButton
    Return
}
```
The script works as intended in Chrome. Unfortunately, it sends Alt-Left in any other program/window as well, thus rendering the primary clipboard useless (the else-part is redundant, of course, but was added as an experiment; its inclusion did not change anything, though).

I would appreciate a comment or advice.

**Comment by SN-CH** [comment]
Oh, yes, I use Lubuntu 20.04 64-bit (LXQt + Openbox), if it matters in this case.

**Comment by phil294** [comment]
Hi, thanks for the kind words! The script won't work because you can't use `IfWinActive` for hotkey definitions, instead they are for regular control flow code. `MButton::` is a hotkey definition, not a line of code to run, so `If` etc don't work here.

Your code is roughly equivalent to:

```ahk
IfWinActive, ahk_class Google-chrome
{
    Send, !{Left}
    Return
}
Else
{
    Send, MButton
    Return
}
Return

MButton::
Send, !{Left}
Return

$MButton::
Send, MButton
Return
```

What you'd want is the `#IfWinActive` *directive* instead: https://www.autohotkey.com/docs/v1/lib/_IfWinActive.htm However, this link is from Windows AHK docs, the directive doesn't yet exist in AHK_X11 (but still planned some day).

So for now you'll have to write your own logic.

```ahk
~MButton:: ; ~ to keep the normal functionality
IfWinNotActive, ahk_class Google-chrome
  Return
Send, !{Left}
Return
```
not tested but this should work
