### ISSUE TITLE
command '#ifwinactive' not found but its already on script

### ISSUE THREAD

**Issue by ASERPRO45** [phil294/AHK_X11#83]
![image](https://github.com/phil294/AHK_X11/assets/97183759/e2a75d90-afb8-499d-87dd-00c6332a161b)

**Comment by xlscode** [comment]
Let me respond to your report on behalf of the Author (I hope the Author will forgive me for arrogantly throwing my two cents in here, but I think this issue is quite obvious and I hope to be able to save Him a bit of time.)

The directive #IfWinActive does not work (for now, at least) in AHK_X11. In the issue #78 (reported by SN-CH on Apr 11) the Author replies:

> What you'd want is the \#IfWinActive directive instead: <https://www.autohotkey.com/docs/v1/lib/_IfWinActive.htm>) However, this link is from Windows AHK docs, the directive doesn't yet exist in AHK_X11 (but still planned some day).

Please, take a look at the rest of the post where you will find a workaround. The link is here:

<https://github.com/phil294/AHK_X11/issues/78#issuecomment-2050740989>

**Comment by phil294** [comment]
thanks @xlscode!

**Comment by xlscode** [comment]
No problem. Glad I could help a bit.
